name = "HumanReadableFormatter"
uuid = "7e4ca075-4d34-493d-967e-c90e13cf6bf4"
authors = ["Chayan Datta <chayan.datta1996@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
